# Generated by Django 5.1.6 on 2025-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_tracking_number_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review', max_length=100),
            preserve_default=False,
        ),
    ]
