# Generated by Django 5.1.6 on 2025-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250417_1038'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE store_review ADD COLUMN updated_at datetime DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE store_review DROP COLUMN updated_at;"
        ),
    ]
