# Generated by Django 5.1.6 on 2025-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20250417_1042'),
    ]

    operations = [
        # All required columns already exist, so we're adding a fake migration
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL statement
            reverse_sql="SELECT 1;"
        ),
    ]
