# Generated by Django 5.2 on 2025-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingconfig_shippingrate_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['rate_type', 'country', 'region', 'cost'], 'verbose_name': 'Shipping Rate', 'verbose_name_plural': 'Shipping Rates'},
        ),
        migrations.RenameField(
            model_name='shippingrate',
            old_name='rate',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If checked, shipping will be free regardless of cost'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount for this rate to apply', max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='pincode_from',
            field=models.CharField(blank=True, help_text='Start of pincode range', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='pincode_to',
            field=models.CharField(blank=True, help_text='End of pincode range', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='rate_type',
            field=models.CharField(choices=[('nationwide', 'Nationwide'), ('regional', 'Regional'), ('city', 'City'), ('pincode', 'Pincode'), ('pincode_range', 'Pincode Range')], default='nationwide', max_length=20),
        ),
    ]
